version: '3'
services:
  web:
    build: .
    ports:
      - "7777:7777"
    links:
      - redis # links this container to "redis" container
  redis:
    image: "bitnami/redis:latest"
    ports:
      - "6379:6379"
    expose:
      - "6379"